"""empty message

Revision ID: 6be60d6184c0
Revises: 
Create Date: 2024-09-08 19:42:14.753770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be60d6184c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('student_id', sa.String(length=20), nullable=True),
    sa.Column('profile_pic', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_asked', sa.DateTime(), nullable=False),
    sa.Column('is_answered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forum_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('found_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('colour', sa.String(length=50), nullable=True),
    sa.Column('additional_info', sa.String(length=500), nullable=True),
    sa.Column('date_found', sa.DateTime(), nullable=False),
    sa.Column('location_found', sa.String(length=100), nullable=False),
    sa.Column('found_by_id', sa.Integer(), nullable=False),
    sa.Column('claimed_by_id', sa.Integer(), nullable=True),
    sa.Column('is_claimed', sa.Boolean(), nullable=True),
    sa.Column('date_claimed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claimed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['found_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lost_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('colour', sa.String(length=50), nullable=True),
    sa.Column('additional_info', sa.String(length=500), nullable=True),
    sa.Column('date_lost', sa.DateTime(), nullable=False),
    sa.Column('location_lost', sa.String(length=100), nullable=False),
    sa.Column('lost_by_id', sa.Integer(), nullable=False),
    sa.Column('found_by_id', sa.Integer(), nullable=True),
    sa.Column('is_found', sa.Boolean(), nullable=True),
    sa.Column('date_found', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['found_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['lost_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('found_item_id', sa.Integer(), nullable=True),
    sa.Column('lost_item_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['found_item_id'], ['found_item.id'], ),
    sa.ForeignKeyConstraint(['lost_item_id'], ['lost_item.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forum_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['forum_post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forum_tag',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['forum_post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    op.create_table('found_item_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('found_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['found_item_id'], ['found_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lost_item_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('lost_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lost_item_id'], ['lost_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lost_item_image')
    op.drop_table('found_item_images')
    op.drop_table('forum_tag')
    op.drop_table('forum_comment')
    op.drop_table('communication')
    op.drop_table('lost_item')
    op.drop_table('found_item')
    op.drop_table('forum_post')
    op.drop_table('faq')
    op.drop_table('user')
    op.drop_table('tag')
    # ### end Alembic commands ###
